import "./globals.css";
import { Outfit as OutfitFont, Ovo as OvoFont } from "next/font/google";

const Outfit = OutfitFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "font-Outfit"  
});

const Ovo = OvoFont({
  subsets: ["latin"],
  weight: ["400"],
  variable: "font-Ovo"
});

export const metadata = {
  title: "My Protfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth select-none">
      <body className={`${Outfit.className} ${Ovo.variable} antialiased overflow-x-hidden leading-8 dark:bg-darkTheme dark:text-white`}>
        {children}
      </body>
    </html>
  );
}
